### ISSUE TITLE
App breaks on the re-authentication process again

### ISSUE THREAD

**Issue by ifat420** [kinngh/shopify-nextjs-prisma-app#32] opened 2023-08-25 06:44 UTC
My app is already installed on a store. If I go to re-auth process again with this(https://ngrok-url.io/api/auth?shop=storename.myshopify.com) URL app breaks with this error

node version: 18.9.0
OS: Mac Os

![Screenshot at Aug 25 12-42-17](https://github.com/kinngh/shopify-nextjs-prisma-app/assets/12673582/b8fb64ae-7dc4-44bc-b33f-a49ffae65edf)

**Comment by kinngh** [comment] 2023-08-25 06:52
Has there been any modifications to the auth process? I need some more info on what's happening so I can debug and deploy a fix^

**Comment by ifat420** [comment] 2023-08-25 08:15
My current node version v18.9.0

I didn't do any modification just clone the repo update .env and install the app in a store. 
After that when I go to the re-auth process again the app breaks with the above screenshot message. 

I have tried with this [repo](https://github.com/kinngh/shopify-editions-summer-2023) it working fine. 
But this issue is only occurring in your current repo.

**Comment by kinngh** [comment] 2023-08-25 10:09
Can you screen record this so I can see a viable way of reproducing this error?

**Comment by kinngh** [comment] 2023-08-25 10:24
I just made a fresh pull and reinstalled, can't replicate the error.

**Comment by ifat420** [comment] 2023-08-25 11:30
sure @kinngh . 
Video [link](https://www.loom.com/share/594d1b56e0fb493d8b99436981def24c?sid=ef3d6d13-f1a1-473b-b462-53d934393485)

**Comment by kinngh** [comment] 2023-08-25 11:43
@ifat420 DM me on Twitter, ye? Let's hop on a call. I want to see this issue because you're moving too fast and there's near 0 information in it.

**Comment by kinngh** [comment] 2023-08-25 12:15
Fix: Update Node to 18 LTS. The node version `18.9.0` was the error. Updating the Node version immediately fixed the errors.

**Closed by kinngh** 2023-08-25 12:15 UTC
Labels: question
